### ISSUE TITLE
Consider using a known license

### ISSUE THREAD

**Issue by davidhedlund** [n8chz/prostetnic#8]
I appreciate that you distribute this software as free. However, adding custom licensed softwares requires professional software licensing consultation to add this add-on to places like directory.fsf.org.

See https://www.gnu.org/licenses/ for the most well known free software licenses.

**Comment by n8chz** [comment]
I'm aware of FSF's principle that copyright precedes copyleft.  As far as I know, CC-0 is the most permissive license available (second to Cypherpunks' Anti License, if it were a license, which it's not).  Would CC-0 pass your organization's muster without legal hand-wringing?

**Comment by davidhedlund** [comment]
@n8chz Indeed, Cypherpunks' Anti License is not a license, it is a public domain declaration.  It is
written in a legally confused way: it uses the misleading vague term "IP".

If you really want to put a work in the public domain, CC0 is better.
However, if you want to allow completely unlimited use of nontrivial
program code, we recommend you release it under Apache 2.0 (which has
a useful patent retaliation feature) rather than putting it in the
public domain.

For a substantial program, it is better in most cases to copyleft it.

See http://gnu.org/licenses/license-recommendations.html.

**Comment by davidhedlund** [comment]
@n8chz Thank you for choosing CC0. I just want you to know that the HTML is broken in https://addons.mozilla.org/en-US/firefox/addon/prostetnic/license/2.0.5.1-signed

**Comment by davidhedlund** [comment]
@n8chz Can you please fix the HTML in https://addons.mozilla.org/en-US/firefox/addon/prostetnic/license/[current version]?

**Comment by davidhedlund** [comment]
[mylabel:open](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aopen%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
[mylabel:license](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Alicense%22+in%3Acomments&type=Issues&ref=searchresults)
